### ISSUE TITLE
Transformations are lost during import/export

### ISSUE THREAD

**Issue by anvpetrov** [mpostument/grafana-sync#41]
Transformations are lost during import/export.
We have some dashboards with tables and they have transformations.
Look at screenshots
![image](https://user-images.githubusercontent.com/39050773/151493959-e281855a-7b74-4769-9eab-75f163245e73.png)
![image](https://user-images.githubusercontent.com/39050773/151494082-fe52d345-a8a3-4d4a-8734-26ea4476c8d3.png)

After import transforms are empty
![capacity_broken](https://user-images.githubusercontent.com/39050773/151494665-0f6ab78f-42c2-45e5-8759-ba97d4a03d6e.png)

**Comment by mpostument** [comment]
Thank you, i will take a look at this issue

**Comment by telmich** [comment]
A heads up on this one: when trying to import/export between two grafana instances, both version 9.0.1, I get the following behaviour:

- the dashboards shows up, but all panels are empty
- on edit / after pushing the "options" button, the metrics begin to appear
- I have to repeat this for every panel

Additionally the colours / thresholds / etc. are all gone.

Asides from these two flaws, the import works quite fine.

**Comment by mpostument** [comment]
> A heads up on this one: when trying to import/export between two grafana instances, both version 9.0.1, I get the following behaviour:
> 
> * the dashboards shows up, but all panels are empty
> * on edit / after pushing the "options" button, the metrics begin to appear
> * I have to repeat this for every panel
> 
> Additionally the colours / thresholds / etc. are all gone.
> 
> Asides from these two flaws, the import works quite fine.

Haven't tried yet to use grafana 9. Maybe that grafana SDK do not have grafana 9 support yet

**Comment by mpostument** [comment]
Transformation should be solved by this PR https://github.com/grafana-tools/sdk/pull/217
Once it merged i will update code to use it

**Comment by lxshopping** [comment]
Has this been solved? This problem is still found in version 1.7

**Comment by mpostument** [comment]
No, not fixed yet. PR to grafana sdk is not merged yet
